### ISSUE TITLE
AirPods Pro Possible

### ISSUE THREAD

**Issue by ITRecords38** [Acidham/uebersicht-airpod-status#1]
Hi,

is it possible to make it compatible with AirPods Pro ?

Thanks

**Comment by Acidham** [comment]
It should...I am using AirPod pro and normal AirPods.

What is the name of your AirPod pro? The script is looking for Bluetooth devices containing "AirPod". That is maybe the issue.

**Comment by ITRecords38** [comment]
Hi,

Good news

I'm testing tonight. Name: Airpods Pro | ITRecords

Thanks

**Comment by ITRecords38** [comment]
Hi,

I just tested and everything works perfectly. perfect. I love 😀

can your update the image for the AirPods pro. Possible ?

Thanks

**Comment by ITRecords38** [comment]
My Update :)

![airpodspro](https://user-images.githubusercontent.com/19632490/84934799-1cc02380-b0d8-11ea-9639-fa770f14135b.jpg)

**Comment by Acidham** [comment]
Send the icon too and I will add it or PullRequest

**Comment by ITRecords38** [comment]
> Send the icon too and I will add it or PullRequest

![airpodPro](https://user-images.githubusercontent.com/19632490/84936903-43cc2480-b0db-11ea-8557-f9f79969cbc3.png)
![noairpodPro](https://user-images.githubusercontent.com/19632490/84936909-44fd5180-b0db-11ea-8dfd-2009725e10ff.png)

**Comment by Acidham** [comment]
done

**Comment by ITRecords38** [comment]
Hi,

Thanks 😉
