### ISSUE TITLE
Small tweak on bt.py - operating error on the python string

### ISSUE THREAD

**Issue by jabackes** [Acidham/uebersicht-airpod-status#3]
Was getting a white box on a fresh install of the widget... I suggest the following change on line 95 on bt.py

currently reads:
`        if left is not "" or right is not "":`

which in my case was throwing this error (discovered by trying to run the code via terminal)

> Application Support/Übersicht/widgets/AirPods.widget/bt.py:95: SyntaxWarning: "is not" with a literal. Did you mean "!="?
>   if left is not "" or right is not "":
> 

So if we adjust the line 95 to read:

`            if left != "" or right != "": `

it runs perfectly.

**Comment by Acidham** [comment]
I already fixed that bug but did not commit :/ Thank you for heads up!
