### ISSUE TITLE
Blueutil - HomeBrew - Apple Silicon - M1

### ISSUE THREAD

**Issue by DocDeleau** [Acidham/uebersicht-airpod-status#4]
Hi and thank you for your work.
I 'm here only to say that with Homebrew on M1 "blueutil" is located at "/opt/homebrew/Cellar/blueutil/2.8.0/bin/blueutil".
I got the widget working modifying a line in the bt.py by myself.

**Comment by Acidham** [comment]
That sounds weird, and I am not aware that HB on M1 behaves differently than on other CPUs. There must be something wrong on your Homebrew setup? Did you run research on why Homebrew installs exec on Cellar in opt?

**Comment by DocDeleau** [comment]
I think that /opt/homebrew is the default installation folder for HomeBrew on M1 Macs.

Andrea Dell'Acqua
Psichiatra | Dipartimento di Salute Mentale - Salerno

Il 6 mag 2021, 19:08 +0200, Acidham ***@***.***>, ha scritto:

**Comment by Acidham** [comment]
I implemented a switch path based on CPU. Can you please test and let me know if it works?

**Comment by DocDeleau** [comment]
Sure, as soon as I get back home.

Andrea Dell'Acqua
Psichiatra | Dipartimento di Salute Mentale - Salerno

Il 7 mag 2021, 16:18 +0200, Acidham ***@***.***>, ha scritto:

**Comment by DocDeleau** [comment]
Sorry, I’ve been late...
No it is not working.
If I enable interaction and copy the error message I get this:
/bin/sh: /usr/local/bin/blueutil: No such file or directory
Traceback (most recent call last):
  File "AirPods.widget/bt.py", line 120, in

I attach the bt.py file I modified in the previous version.
Il 7 mag 2021, 16:18 +0200, Andrea Dell'Acqua ***@***.***>, ha scritto:

**Comment by Acidham** [comment]
That's weird. What is the output of the following command when you execute it in shell?

`python3 -c "import platform;print(platform.processor())"`

**Comment by DocDeleau** [comment]
The output is:
arm

Andrea Dell'Acqua
Psichiatra | Dipartimento di Salute Mentale - Salerno

Il 8 mag 2021, 23:39 +0200, Acidham/uebersicht-airpod-status ***@***.***>, ha scritto:
>
> python3 -c "import platform;print(platform.processor())"

**Comment by Acidham** [comment]
I added another solution. Please download the updated widget and ensure that Shell Commands "Load Bash env" is enabled in Uebersicht Preferences

**Comment by DocDeleau** [comment]
Nothing to do...
This is the output:
/bin/sh: --paired: command not found
Traceback (most recent call last):
  File "AirPods.widget/bt.py", line 118, in
    main()
  File "AirPods.widget/bt.py", line 110, in main
    connected_list = get_device_html()
  File "AirPods.widget/bt.py", line 91, in get_device_html
    airpods: list = paired_airpods()
  File "AirPods.widget/bt.py", line 70, in paired_airpods
    jsn = json.loads(os.popen(cmd).read())
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

Andrea Dell'Acqua
Psichiatra | Dipartimento di Salute Mentale - Salerno

Il 10 mag 2021, 11:50 +0200, Acidham ***@***.***>, ha scritto:

**Comment by Acidham** [comment]
Did you set a checkmark on Shell Commands? 

<img width="648" alt="Screen Shot 2021-05-10 at 14 14 38" src="https://user-images.githubusercontent.com/17712121/117657746-38be2f00-b19a-11eb-8547-90e1e67f7d4a.png">

what is the result of the following command: `which blueutil`

**Comment by DocDeleau** [comment]
Yes I did, while the output of “which blueutil” is: /opt/homebrew/bin/blueutil

Andrea Dell'Acqua
Psichiatra | Dipartimento di Salute Mentale - Salerno

Il 10 mag 2021, 14:17 +0200, Acidham ***@***.***>, ha scritto:

**Comment by Acidham** [comment]
There must be something wrong with either your env (PATH). I am executing `which blueutil` inside my script and this command response the path to executable (blueutil) but it seems nothing is returned. 

Can you run `echo $PATH` in terminal? What is the result?

**Comment by DocDeleau** [comment]
MacBook-Pro-di-Andrea ~ % echo $PATH
/opt/homebrew/bin:/opt/homebrew/sbin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin

Andrea Dell'Acqua
Psichiatra | Dipartimento di Salute Mentale - Salerno

Il 10 mag 2021, 19:42 +0200, Acidham/uebersicht-airpod-status ***@***.***>, ha scritto:
>
> echo $PATH

**Comment by Acidham** [comment]
Are you able to exec `blueutil -v` from terminal?

**Comment by DocDeleau** [comment]
blueutil -v
2.8.0

Andrea Dell'Acqua
Psichiatra | Dipartimento di Salute Mentale - Salerno

Il 11 mag 2021, 12:03 +0200, Acidham ***@***.***>, ha scritto:

**Comment by Acidham** [comment]
ok in this case it seems Ueberischt is loading bash instead of zsh (default on newer macs)

Let's try the following: 
1. open `~/.bashrc` in editor
2. add `export PATH=/opt/homebrew/bin:/opt/homebrew/sbin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin`
3. save

try again

**Comment by DocDeleau** [comment]
It is working now.

Andrea Dell'Acqua
Psichiatra | Dipartimento di Salute Mentale - Salerno

Il 11 mag 2021, 13:09 +0200, Acidham ***@***.***>, ha scritto:

**Comment by Acidham** [comment]
Ok thank for testing. Uebersicht seems to load bash env instead of zsh env, which is new default for macOS. 

Closing the issue for now.
