### ISSUE TITLE
Errno 2: no such file

### ISSUE THREAD

**Issue by AtlanGit** [Acidham/uebersicht-airpod-status#6]
Dear Acidham,

for some reason the bt.py doesn't run:
<img width="1339" alt="image" src="https://user-images.githubusercontent.com/26897517/204102792-5203e8c0-0ac5-418b-9a2f-c6c099c2099e.png">
I tried everything but I didn't manage to get the bt.py to run.

**Comment by AtlanGit** [comment]
I use the AirPods Pro 2 and macOS 12.6.

**Comment by AtlanGit** [comment]
removing the path and just executing python leads to:
<img width="293" alt="image" src="https://user-images.githubusercontent.com/26897517/204103094-e563011b-47ec-4714-a899-4636b8ec673e.png">

**Comment by Acidham** [comment]
What is your widget folder? sems the `bt.py` cannot be found

**Comment by AtlanGit** [comment]
I just used the normal one and copied it in.

**Comment by Acidham** [comment]
Can you execute the file with the path on command line with `python3 <path to by.py>` ?

**Comment by AtlanGit** [comment]
So I use:
`command: 'python3 AirPods.widget/bt.py'`
and the location is in widget/uebersicht-airpod-status-master/AirPods.widget/

**Comment by Acidham** [comment]
the absolute path not relative path

**Comment by AtlanGit** [comment]
I tried to copy the path in but it didn't help either
`command: 'python3 /Users/[user]/Library/Application Support/Übersicht/widgets/uebersicht-airpod-status-master/AirPods.widget/bt.py'`

<img width="1126" alt="image" src="https://user-images.githubusercontent.com/26897517/204112562-e95b87f7-bedf-4d97-91da-1e83f493ebd7.png">

**Comment by Acidham** [comment]
ok again...see the error your file is not found! please try to execute the command on terminal. you must see an output at least! 

In Uebersicht preferences change path to an easier an shorter path and try to execute.

**Comment by AtlanGit** [comment]
I get the same error on the terminal, and I have no idea why. The path is right for sure, and when I move the file to the desktop it can run it

**Comment by Acidham** [comment]
Maybe it is because the path contains `…/Application Support/…` and needs to be encoded poperly. I am storing my widgets in `/Users/<user>/ueberischtwidgets`

**Comment by AtlanGit** [comment]
I fixed the `.../Application Support/...` by putting it into quotes `.../"Application Support"/...`, so now I can open it but now I ran into another error/other errors:

`Traceback (most recent call last):
  File "/Users/<user>/Library/Application Support/Übersicht/widgets/uebersicht-airpod-status-master/AirPods.widget/bt.py", line 96, in <module>
    main()
  File "/Users/<user>/Library/Application Support/Übersicht/widgets/uebersicht-airpod-status-master/AirPods.widget/bt.py", line 88, in main
    connected_list = get_device_html()
  File "/Users/<user>/Library/Application Support/Übersicht/widgets/uebersicht-airpod-status-master/AirPods.widget/bt.py", line 69, in get_device_html
    airpods: list = paired_airpods()
  File "/Users/<user>/Library/Application Support/Übersicht/widgets/uebersicht-airpod-status-master/AirPods.widget/bt.py", line 39, in paired_airpods
    devices: dict = jsn['SPBluetoothDataType'][0]['devices_list']
KeyError: 'devices_list'
<user>@MacBook-Air-von-<user> ~ % 
`

I also duplicated the file just incase and put it into a location without any spaces, but the errors above still occurs

**Comment by Acidham** [comment]
Oh forgot to push the new version. Please download again from repo

**Comment by AtlanGit** [comment]
Works better, just the images don't connect yet
<img width="286" alt="image" src="https://user-images.githubusercontent.com/26897517/204141975-587aa839-cb7e-485b-b58a-ac69dbf5fb7a.png">
Thanks for your help already!

**Comment by Acidham** [comment]
Great so far! Can you open the AirPods.widget directory and check if there is a file called `airpodpro.png`?

**Comment by AtlanGit** [comment]
<img width="759" alt="image" src="https://user-images.githubusercontent.com/26897517/204143369-2193c766-9816-4191-927c-a465104dce30.png">
yep, they are all there
I also tried another location in case there is a problem with the space
Also, I ran it threw the terminal and he does try to open the right location and the right picture

**Comment by AtlanGit** [comment]
Also, I tried to open the case directly (in the new location):
`NO_BT_IMG = f'<img class="s-img" src="/Users/<user>/AirPods.widget.pack/case.png">'`
Didn't change anything:
<img width="287" alt="image" src="https://user-images.githubusercontent.com/26897517/204144058-3164d93b-bbc2-4e31-9ce6-13b13bec4622.png">

**Comment by Acidham** [comment]
Is the path correct in `src`? what happens when you open `/Users/<user>/AirPods.widget.pack/case.png` in you browser?

Can you popen the `case.png` in preview?

**Comment by AtlanGit** [comment]
yes, the path is correct, I can open it in the browser as well as open it via preview
The same problem occurs if I'm connected as well

**Comment by Acidham** [comment]
that's strange. can you see an error in Uebersicht console?

**Comment by AtlanGit** [comment]
Not in the console itself, but I found:
<img width="993" alt="image" src="https://user-images.githubusercontent.com/26897517/204144605-0d3e0bfb-cbb9-4738-8ae8-3b4f2a7aed1e.png">
<img width="663" alt="image" src="https://user-images.githubusercontent.com/26897517/204144647-9a02b7be-9519-4305-aed8-feb2ac0eefc8.png">
<img width="513" alt="image" src="https://user-images.githubusercontent.com/26897517/204144777-ffdb916c-0b22-4202-bdbe-092188c6b65b.png">

**Comment by Acidham** [comment]
Can you please download again. I pushed the files again to GIT.

**Comment by AtlanGit** [comment]
Same problem, still no errors

**Comment by Acidham** [comment]
No idea what is wrong…Are you using other uebersicht widgets? Are those functioning properly?

**Comment by AtlanGit** [comment]
Im out of ideas as well, removing all other widgets doesn't do a thing

**Comment by Acidham** [comment]
did you try to re-install Uebersicht?

**Comment by AtlanGit** [comment]
<img width="1002" alt="image" src="https://user-images.githubusercontent.com/26897517/204148145-56f60a0a-4eb6-4d4b-883e-ce4447841a0e.png">
Ill reinstall in a sec
that's an error I get without any widgets,  idk if it helps

**Comment by AtlanGit** [comment]
The error mentioned above went away but the pictures still do not load

**Comment by AtlanGit** [comment]
I changed to those 2:
`ICON_PATH = "file:///Users/<user>/Library/Application%20Support/U%CC%88bersicht/widgets/uebersicht-airpod-status-master/AirPods.widget/"
HTML_SPACER = "&nbsp;"
NO_BT_IMG = f'<img class="s-img" src="{ICON_PATH}case.png">'  # Icon for AirPods disconnected`
Wired enough, that's what I get now:
<img width="280" alt="image" src="https://user-images.githubusercontent.com/26897517/204151274-f14280c7-cad1-4274-9d52-798d54587e5d.png">
<img width="279" alt="image" src="https://user-images.githubusercontent.com/26897517/204151462-cff07d3e-00a6-488e-81b0-8e58f6ade03c.png">
the same happens, if I put a false link in
Using a dropbox instant download link works tho

**Comment by AtlanGit** [comment]
So, that's what Ive went with:
`ICON_PATH = "https://www.dropbox.com/s/xgbek9dcsm29px8/" #changed here
#ICON_PATH = "file:///Users/<user>/Library/Application%20Support/U%CC%88bersicht/widgets/uebersicht-airpod-status-master/AirPods.widget/" #changed here
HTML_SPACER = "&nbsp;"
NO_BT_IMG = f'<img class="s-img" src="{ICON_PATH}case.png?dl=1">'  # Icon for AirPods disconnected`

I also changed:
`<img src="{ICON_PATH}{product}.png?dl=1">`

That worked completely fine, but I have no idea at all why the old one didn't; could it maybe be with the permissions?

**Comment by Acidham** [comment]
Glad that worked but seems that permissions does not allow to access file in that location. I would recommend to move widget directory somewhere else.
